BIBSYSDEV/NVA-scenarios

26-register_publication/1409-creator_selects_publication_in_journal_and_peer_review_details_are_hidden.feature
mvp.feature

Refactor NP-1409 Creator selects Publication in Journal and Peer review is hidden

add feature 1409

---

1216-menu/346-users_sees_the_menu_for_creator.feature

Removed menu item not in application

Creator menu

---

1216-menu/346-users_sees_the_menu_for_creator.feature
1217-my_profile_page/411-user_adds_an_institution_from_my_profile.feature
1221-my_publication/354-creator_opens_my_publications.feature

Np 1648 Fixes for publication renamed to registrations

---

26-register_publication/1624-creator_navigates_to_the_reference_tab_and_selects_reference_type_other_publication.feature

Feature for main type "Other publication"

add feature for main reference type other publication

---

26-register_publication/1624-creator_navigates_to_the_reference_tab_and_selects_reference_type_other_publication.feature
26-register_publication/1631-creator_selects_reference_type_other_publication_and_selects_subtype_map.feature

Feature for reference type "Other publication" and subtype "Map"

add subtype map

---

26-register_publication/1632-creator_selects_reference_type_other_publication_and_selects_subtype_musical_notation.feature

add subtype musical notation

---

26-register_publication/1669-creator_selects_reference_type_other_publication_and_selects_subtype_feature_article.feature

add subtype feature article

---

1217-my_profile_page/1724-non-customer_views_my_profile.feature
1217-my_profile_page/1725-user_without_any_roles_views_my_profile.feature

Adding features for the following functionality:

New features my profile

---

1221-my_publication/913-users_sees_published_publications.feature
1224-user_administration/1363-administrator_assigns_a_role_to_a_user_part_i.feature
1224-user_administration/1424-institution_administrator_configures_automatic_creator_role.feature
1224-user_administration/1491-user_is_assigned_creator_role_according_to_settings_for_their_customer_institution.feature
1224-user_administration/359-administrator_views_user_administration_sections_with_role_members_part_i.feature
1224-user_administration/363-administrator_opens_the_add_role_page_part_i.feature
1228-public_page/881-view_public_page_for_publication.feature
1237-registrator_worklist/1238-creator_opens_my_messages.feature
1237-registrator_worklist/1246-creator_views_details_of_an_item_in_the_messages_list.feature
26-register_publication/1409-creator_selects_publication_in_journal_and_peer_review_details_are_hidden.feature
26-register_publication/392-creator_navigates_to_the_reference_tab_and_selects_book.feature
26-register_publication/443-creator_begins_registering_a_registration_in_the_wizard.feature
mvp.feature
not_mvp/1224-user_administration/1313-administrator_views_user_administration_sections_with_role_members_part_ii.feature
not_mvp/1224-user_administration/1314-administrator_assigns_a_role_to_a_user_part_ii.feature

Options in Scenario Outline need to quoted for Cypress to be able to match strings

NP-1957 Quoted options in scenario outlines

---

26-register_publication/creator_selects_reference_type_contribution_to_journal_and_selects_subtype.feature

Lagt til nye subtyper `Kronikk` og `Intervju` for `Publikasjon i tidsskrift`.

NP-1659 Add Chronicle and Interview

---

26-register_publication/543-creator_begins_wizard_registration_and_navigates_to_description_tab.feature
26-register_publication/creator_navigates_to_the_reference_tab_and_selects_reference_type_book.feature

Flytter felt for "Fagfelt i NPI" til å bare vises for bøker.

Move NPI discipline to reference tab

---

26-register_publication/1694-creator_selects_reference_type_student_thesis_and_selects_subtype.feature

Viste seg at det trengs Examples for begge scenarioene

Subtypes for student thesis

---

1223-curator_worklist/358-curator_opens_a_registration_from_a_doi_request.feature

Split into two cases; draft and published registration

Changes to scenario for open registration from a DOI request

---

26-register_registration/creator_navigates_to_description_tab.feature
mvp.feature

Oppdater feil Jira-nummer, og fjern scenario fra mvp som er flyttet over

Fix jira number

---

26-register_registration/creator-navigates-to-contributor-tab.feature

Need to add spaces before and after ´/´ to be able to test it. Without the spaces it counts as Alternative text in Cucumber. 
See: https://cucumber.io/docs/cucumber/cucumber-expressions/#alternative-text
Also due to the way the cucumber addon works in Cypress two steps in the same Scenario cannot be the same if it's supposed to test different things.

Changes to feature to make it testable

---

1221-my_publication/355-creator_opens_an_item_in_my_registrations_list.feature
1228-public_page/1231-owner_navigates_to_the_public_page_for_publication_for_published_publication_without_doi.feature
1228-public_page/owner_navigates_to_the_landing_page_for_their_registration.feature

Vis liste med alle valideringsfeil på Landing Page og Wizard (ikke ved førstegangsregistrering)

Show error list

---

26-register_registration/creator-navigates-to-contributor-tab.feature

https://unit.atlassian.net/browse/NP-2467 må endres til å bli en Story (`Creator verifies Contributor`)

NP-2468 Add scenarios for verifying Contributor

---

1208-projects/project_landing_page.feature

Scenarios for Project Landing Page

NP-2624 Add Scenarios for project landing page

---

26-register_registration/creator_navigates_to_resource_type_tab.feature

Diverse endringer av typer for Journal ref nye skisser.

Update types for Journal

---

26-register_registration/275-creator_navigates_to_files_and_license_tab.feature

Revidering etter ny runde med skisser. Tror vi kan slette en story (2635) siden det nå blir bare ett steg for å legge til link

Update flow for adding link

---

26-register_registration/resource_types/creator_selects_resource_type_report.feature

Np 2775 report type

---

26-register_registration/resource_types/creator_selects_resource_type_presentation.feature

Scenario for Presentation type

NP-2766 Add scenarios for Presentation types

---

26-register_registration/resource_types/creator_selects_resource_type_degree.feature

Oppdater scenario for studentoppgaver

Update degree scenarios

---

26-register_registration/resource_types/creator_selects_resource_type_chapter.feature

Oppdatering av del av bok/rapport

NP-2769 Update chapter types

---

1228-public_page/anonymous_user_views_landing_page_for_registration.feature

Legg til knapper for å dele link til Landing Page via epost, facebook, linkedin og twitter

Add sharing buttons

---

1226-editor/publishings_rights.feature
1226-editor/readme
1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature

Created publishing_rights.feature
Have adjusted readme and owner_navigate_to_the_landing_page_for_theire_registration (sic!)  accordingly

Editor decide publishing policy

---

1223-curator_worklist/my_worklist_approval.feature
1226-editor/publishings_rights.feature
1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature

10 scenarios marked @needJiraTagApproval

Implement Approval Scenarios

---

24-authentication/user-logs-in.feature

Duplicates @384 - User creates a new Author identity

Removed 2 duplicate scenarios from user-logs-in.feature

---

1223-curator_worklist/my_worklist_approval.feature
1226-editor/nvi_report.feature
nvi/nvi_institution.feature
nvi/readme
nvi/registration_nvi_resource.feature
nvi/validation_nvi_resource.feature

The first scenarios to frame the NVI support in NVA.

Conceptual NVI process support

---

26-register_registration/2461-creator-adds-a-contributor.feature
26-register_registration/creator-navigates-to-contributor-tab.feature

Legger til Scenario for hvilke typer Contributors som skal kunne legges til direkte basert på type.
Legger også til info om nye typer (Presentation og Artistic)

Update contributor scenarios

---

26-register_registration/resource_types/creator_selects_resource_type_contribution_to_journal.feature

Legger til ny subtype `Conference abstract` / `konferanseabstrakt`

Add new subtype conference abstract

---

26-register_registration/resource_types/creator_selects_resource_type_degree.feature

Legger til ny type `Licentiate thesis` / `Lisensiatavhandling`

Add licentiate thesis type

---

26-register_registration/resource_types/creator_selects_resource_type_book.feature

Legg til ny innholdstype `Exhibition catalog` / `Utstillingskatalog` for Monograf

Add new content type Exhibition Catalog for BookMonograph

---

26-register_registration/resource_types/creator_selects_resource_type_report.feature

Legg til `Abstract collection` / `Abstraktsamling`

Add abstract collection subtype to Report

---

26-register_registration/resource_types/creator_selects_resource_type_chapter.feature

Legg til Conference Abstract som subtype for Chapter.

Add Conference abstract subtype

---

26-register_registration/resource_types/artistic_result/creator_selects_resource_type_artistic_result_and_subtype_architecture.feature

Trenger en nøye gjennomgang av om alle navn er beskrivende og gir mening, samt om alle felt er dekket og har logiske navn. Alt som er beskrevet her er basert på skisser i whimsical:

Add scenarios for Artistic Architecture

---

26-register_registration/resource_types/creator_selects_resource_type_press_media.feature
26-register_registration/resource_types/creator_selects_resource_type_press_or_media.feature

Add media type

---

24-authentication/user-logs-in.feature

Endre innloggingsflyt. (Erstatt ARP med Cristin)
Tenker vi ikke trenger en story i Jira for hvert Scenario, men at vi heller lager Tasks med logiske avgrensinger

Add scenario for logging in

---

26-register_registration/resource_types/creator_selects_resource_type_contribution_to_journal.feature

Har lagt inn norsk navn for å tydeliggjøre hvilken verdi det er. Verdien i parentes er verdien vi persisterer.

Update journal types

---

1226-editor/curators_responsibility.feature
1226-editor/editor_opens_editor_administration.feature
1226-editor/readme

Adjusted responsibility scenario

---

26-register_registration/resource_types/artistic_result/creator_selects_resource_type_artistic_result.feature
26-register_registration/resource_types/artistic_result/creator_selects_resource_type_artistic_result_and_subtype_literary_arts.feature
26-register_registration/resource_types/artistic_result/creator_selects_resource_type_artistic_result_and_subtype_visual_arts.feature

Nye typer for Skrivekunst og Visuell kunst. Disse er allerede implementert.

New artistic types

---

26-register_registration/resource_types/creator_selects_resource_type_other_publication.feature

Update scenario for Map type

---

1223-curator_worklist/my_worklist.feature

the details in the introduction to the scenarios according to new terms and latest changes.
Furthermore details will be added.

Updated and cleaned

---

1208-projects/my_projects.feature
1208-projects/project_landing_page.feature
1208-projects/project_wizard.feature

Skisser: https://miro.com/app/board/uXjVOtXaWu0=/

Project scenarios revision

---

1208-projects/project_wizard.feature
26-register_registration/creator_navigates_to_description_tab.feature

Updated scenarios

---

1228-landing_page/curator_navigates_to_the_landing_page_for_registration.feature
1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature

Scenario for publisering of DOI-forespørsel

Np 25355 publish registration

---

1208-projects/readme

Minor typo corrections

---

1217-my_profile_page/352-user_opens_the_page_my_profile.feature
1226-editor/readme
1228-landing_page/landing_page_authenticated_user.feature

Validated contributors with active affiliation and editors may edit metadata.

Added access patterns

---

search/user_searches_for_registration.feature

Adds the workflow concept to search since this affects entries in the search index

Anonymous user searches for publication

---

nvi/nvi-approval-process.feature
nvi/nvi-reset-approval.feature

Ticket: https://sikt.atlassian.net/browse/NP-48112
Changes:
- Add scenarios from Jira ticket that are already approved/planned
- Remove old scenario that overlaps with the new scenarios.

[np-48112] feat: Copy approval status scenarios from Jira
